name: uni_helper
description: "A new Flutter project for students."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Робота з PDF
  pdfx: ^2.5.0
  path_provider: ^2.1.2 

  # Основні пакети Firebase
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.1.0
  shared_preferences: ^2.3.5
  
  # ВІДЖЕТИ (Додано для Android та iOS)
  home_widget: ^0.9.0
  
  # Для парсингу HTML
  http: ^1.2.0
  html: ^0.15.4
  windows1251: ^2.0.1  
  
  # Додаткові пакети
  cupertino_icons: ^1.0.6
  google_sign_in: ^7.2.0
  
  intl: ^0.20.2
  url_launcher: ^6.3.2
  table_calendar: ^3.1.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  share_plus: ^10.1.0
  webview_flutter: ^4.13.1
  
  # Для роботи зі студентським квитком
  image_picker: ^1.0.4
  image: ^4.0.17
  
  # OCR
  google_mlkit_text_recognition: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icon/
    - assets/docs/indyvidual_grafik.pdf
    - assets/docs/stypendia.pdf
    - assets/docs/ugoda_praktyka.pdf
    - assets/docs/student_card.pdf # Додано новий актив
    - assets/docs/dormitory.pdf    # Додано новий актив